Task completed.
IvanLuchkin/race-condition pull request #1
Opened 2021-02-22 14:25 UTC by IvanLuchkin

- Gradle checkstyle added
- Logging added

2021-02-22 15:25 UTC, Mandybur800 approved these changes

2021-02-22 15:55 UTC, Sofasmile requested changes

2021-02-22 15:55 UTC, Sofasmile commented on src/main/java/Counter.java
> +    public void setCount(int count) {
давай замість методу setCount зробимо просто increment() який буде інкрементити на 1 поточне значення і повертати нове значення, яке ми і будемо виводити на екран. Тоді в нас не буде дублювання виводу в лог файлі для двох потоків.

2021-02-22 21:56 UTC, IvanLuchkin commented on src/main/java/Counter.java
> +    public void setCount(int count) {
The doubling will still take place, since it is the whole point of the demonstration (as far as I understood)

2021-02-23 09:20 UTC, Sofasmile commented on src/main/java/Counter.java
> +    public void setCount(int count) {
сенс гонки потоків в тому, щоб показати як кілька потоків змагаються за доступ до одного і того ж ресурсу. І цей доступ вони отримують рандомно. Тобто це є одна із проблем багатопоточки, коли ми не можемо контролювати і знати на перед в який момент, який і потоків буде мати доступ до  ресурсу

2021-02-23 09:20 UTC, Sofasmile approved these changes

2021-02-24 10:57 UTC, merged